### PR TITLE
Update to Atlas 3.0.14

### PR DESCRIPTION
**Pull request by powerofpi**
Trying to get FlowMiner to work with Atlas 3.

@jonmathews-ensoft

### CODE REVIEW

**Comment by powerofpi** [comment]
@jonmathews-ensoft, do the changes thusfar look sane? I think the compilation errors are resolved, but when I test out the mining of summaries, I get an empty result. Probably the semantics of XCSG have changed on me.

**Comment by jonmathews-ensoft** [comment]
So far the changes look sane, although I needed pull request #3 to make it compile and run.  I do have results in the universe, but there were errors in the log while FlowMiner was running and it failed to write the summaries.

**Comment by powerofpi** [comment]
@jonmathews-ensoft, I'm trying to mine summaries for `opencsv-3.9.jar`. If I take the Jimple project that's being generated and look at the universe from indexing it, its only contents are nodes for the primitive Java types and the project- no other contents. Any ideas? Something seems to be preventing Atlas from properly indexing the Jimple project.

**Comment by powerofpi** [comment]
Well... for reasons I can't explain, I set up a fresh Eclipse Neon stack and it "just worked". I don't know what was wrong with my Mars setup. I'll get the updated binary on the update site.

**Pull request merged**
